/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Plate.glb 
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export function Plate(props) {
  const { nodes, materials } = useGLTF('/assets/models/etc/Plate.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plate2.geometry} material={materials.Plate} position={[-0.072, 0.069, -0.111]} scale={[1.363, 0.039, 2.215]} />
    </group>
  )
}

useGLTF.preload('/assets/models/etc/Plate.glb')
