/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ShowCase.glb 
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export function ShowCase(props) {
  const { nodes, materials } = useGLTF('/assets/models/etc/ShowCase.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Case.geometry} material={materials.Case} position={[-3.291, 1.84, -0.062]} scale={[1.578, 2.44, 1.79]} />
      <mesh geometry={nodes.Glass.geometry} material={materials.Glass} position={[-3.291, 1.84, -0.062]} scale={[1.578, 2.44, 1.79]} />
    </group>
  )
}

useGLTF.preload('/assets/models/etc/ShowCase.glb')
