/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 JapaneseRamen.glb 
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export function JapaneseRamen(props) {
  const { nodes, materials } = useGLTF('/assets/models/Food/JapaneseRamen.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.018, -0.371, -0.024]} scale={1.024}>
        <mesh geometry={nodes.Sphere003.geometry} material={materials.Gravy} />
        <mesh geometry={nodes.Sphere003_1.geometry} material={materials.Plate} />
        <mesh geometry={nodes.Sphere003_2.geometry} material={materials.MeatColor1} />
        <mesh geometry={nodes.Sphere003_3.geometry} material={materials.MeatColor2} />
        <mesh geometry={nodes.Sphere003_4.geometry} material={materials.MeatColor3} />
        <mesh geometry={nodes.Sphere003_5.geometry} material={materials.MeatlColor4} />
        <mesh geometry={nodes.Sphere003_6.geometry} material={materials.Egg} />
        <mesh geometry={nodes.Sphere003_7.geometry} material={materials['Egg.001']} />
        <mesh geometry={nodes.Sphere003_8.geometry} material={materials.GreenOnion} />
        <mesh geometry={nodes.Sphere003_9.geometry} material={materials.Noodle} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/Food/JapaneseRamen.glb')
