/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Bricks0.glb 
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export function Bricks0(props) {
  const { nodes, materials } = useGLTF('/assets/models/minigame/Bricks0.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={[1, 0.25, 1]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Grass} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.Soil} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/minigame/Bricks0.glb')
