/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Bricks2048.glb 
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export function Bricks2048(props) {
  const { nodes, materials } = useGLTF('/assets/models/minigame/Bricks2048.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.749, 0]} scale={[0.9, 0.5, 0.9]}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials.BrickMain} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials.BrickSub} />
      </group>
      <group scale={[1, 0.25, 1]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Grass} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.Soil} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/minigame/Bricks2048.glb')
