/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Bricks64.glb 
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export function Bricks64(props) {
  const { nodes, materials } = useGLTF('/assets/models/minigame/Bricks64.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={[1, 0.25, 1]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Grass} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.Soil} />
      </group>
      <group position={[-0.018, 0.844, 0.077]} scale={[0.575, 0.568, 0.487]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.BrickMain} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.BrickSub} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/minigame/Bricks64.glb')
