/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Bricks128.glb 
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export function Bricks128(props) {
  const { nodes, materials } = useGLTF('/assets/models/minigame/Bricks128.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={[1, 0.25, 1]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Grass} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.Soil} />
      </group>
      <group position={[0.001, 0.879, 0.139]} scale={[0.6, 0.568, 0.6]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.BrickMain} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.BrickSub} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/minigame/Bricks128.glb')
