/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 B4Enter2.glb -o B4Enter2.jsx 
*/

import { useBox } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'
import React, { useEffect } from 'react'

export function B4Enter2({position, ...props}) {
  const { scene, nodes, materials } = useGLTF('/assets/models/B4Enter2.glb')
  const [meshRef, api] = useBox(() => ({
    args: [9, 5, 43],
    type: 'Static',
    mass: 1,
    position,
    ...props
  }))

  useEffect(() => {
    scene.traverse((obj) => {
      if(obj.isObject3D) {
        console.log(obj)
        obj.castShadow = true
        obj.receiveShadow = true
      }
    })
  }, [scene])
  return (
    <group ref={meshRef}>
      <mesh geometry={nodes.B4Enter2.geometry} material={materials['858585 (B4,B9,B2)']} position={[0,0,0]} rotation={[0,0,0]} scale={[18.7, 4, 39]} />
    </group>
  )
}

useGLTF.preload('/assets/models/B4Enter2.glb')
