/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 B4Enter.glb -o B4Enter.jsx 
*/

import { useBox } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'
import React, { useEffect } from 'react'

export function B4Enter({position, ...props}) {
  const { scene, nodes, materials } = useGLTF('/assets/models/B4Enter.glb')
  const [meshRef, api] = useBox(() => ({
    args: [20.5, 59, 80],
    type: 'Static',
    mass: 1,
    position,
    ...props
  }))

  useEffect(() => {
    scene.traverse((obj) => {
      if(obj.isObject3D) {
        console.log(obj)
        obj.castShadow = true
        obj.receiveShadow = true
      }
    })
  }, [scene])

  return (
    <group ref={meshRef}>
      <group position={[0,0,0]} rotation={[0,0,0]} scale={[18.615, 4.051, 38.03]}>
        <mesh geometry={nodes.Cube008.geometry} material={materials['E2EBCA (B1,B4,B5,B6(BodyFrame))']} />
        <mesh geometry={nodes.Cube008_1.geometry} material={materials['858585 (B4,B9,B2)']} />
        <mesh geometry={nodes.Cube008_2.geometry} material={materials['D2D2D2 & Metal (B4,B5,B6,B7)']} />
        <mesh geometry={nodes.Cube008_3.geometry} material={materials['C0E8F6 (B1~9(Window))']} />
        <mesh geometry={nodes.Cube008_4.geometry} material={materials['2F0708 (B4,B8,B9(Window Frame),T2(Table))']} />
        <mesh geometry={nodes.Cube008_5.geometry} material={materials['18226AA (Number Plane)']} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/B4Enter.glb')
