/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 B5-Pipe_L.glb -o B5-Pipe_L.jsx 
*/

import { useBox } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'
import React, { useEffect } from 'react'

export function B5Pipe_L({position, ...props}) {
  const { scene, nodes, materials } = useGLTF('/assets/models/B5-Pipe_L.glb')
  const [meshRef, api] = useBox(() => ({
    args: [32, 160, 41],
    type: 'Static',
    mass: 1,
    position,
    ...props
  }))

  useEffect(() => {
    scene.traverse((obj) => {
      if(obj.isObject3D) {
        console.log(obj)
        obj.castShadow = true
        obj.receiveShadow = true
      }
    })
  }, [scene])
  return (
    <group ref={meshRef}>
      <group position={[-5,0,0]} rotation={[0,0,0]} scale={[25, 77.5, 120]}>
        <mesh geometry={nodes.Cube002.geometry} material={materials['61544D (B1,B2,B5,B6(Body)']} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials['E2EBCA (B1,B4,B5,B6(BodyFrame))']} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials['C0E8F6 (B1~9(Window))']} />
        <mesh geometry={nodes.Cube002_3.geometry} material={materials['23683C (RoofTop)']} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/B5-Pipe_L.glb')
