/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 B5.glb -o B5.jsx 
*/

import { useBox } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'
import React, { useEffect } from 'react'

export function B5({position, ...props}) {
  const { scene, nodes, materials } = useGLTF('/assets/models/B5.glb')
  const [meshRef, api] = useBox(() => ({
    args: [57, 205, 285],
    type: 'Static',
    mass: 1,
    position,
    ...props
  }))

  useEffect(() => {
    scene.traverse((obj) => {
      if(obj.isObject3D) {
        console.log(obj)
        obj.castShadow = true
        obj.receiveShadow = true
      }
    })
  }, [scene])
  return (
    <group ref={meshRef}>
      <group position={[-2,0,0]} rotation={[0,0,0]} scale={[25, 77.5, 120]}>
        <mesh geometry={nodes.Cube011.geometry} material={materials['61544D (B1,B2,B5,B6(Body).002']} />
        <mesh geometry={nodes.Cube011_1.geometry} material={materials['000000 & Metal (C2,T2).002']} />
        <mesh geometry={nodes.Cube011_2.geometry} material={materials['18226AA (Number Plane).002']} />
        <mesh geometry={nodes.Cube011_3.geometry} material={materials['E2E2E2(B1~9(Body,Number)).002']} />
        <mesh geometry={nodes.Cube011_4.geometry} material={materials['DCE759 & Metal (DEVName, Statue).002']} />
        <mesh geometry={nodes.Cube011_5.geometry} material={materials['E2EBCA (B1,B4,B5,B6(BodyFrame)).002']} />
        <mesh geometry={nodes.Cube011_6.geometry} material={materials['C0E8F6 (B1~9(Window)).002']} />
        <mesh geometry={nodes.Cube011_7.geometry} material={materials['D2D2D2 & Metal (B4,B5,B6,B7).002']} />
        <mesh geometry={nodes.Cube011_8.geometry} material={materials['23683C (RoofTop).002']} />
        <mesh geometry={nodes.Cube011_9.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane).001']} />
        <mesh geometry={nodes.Cube011_10.geometry} material={materials['0EA6EF (Leaf, Smoking Booth).001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/B5.glb')
