/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 B6.glb -o B6.jsx 
*/

import { useBox } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'
import React, { useEffect } from 'react'

export function B6({position, ...props}) {
  const { scene, nodes, materials } = useGLTF('/assets/models/B6.glb')
  const [meshRef, api] = useBox(() => ({
    args: [51, 205, 280],
    type: 'Static',
    mass: 1,
    position,
    ...props
  }))

  useEffect(() => {
    scene.traverse((obj) => {
      if(obj.isObject3D) {
        console.log(obj)
        obj.castShadow = true
        obj.receiveShadow = true
      }
    })
  }, [scene])

  return (
    <group ref={meshRef}>
      <group position={[-6,0,0]} rotation={[0, 0, 0]} scale={[25, 77.5, 120]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials['61544D (B1,B2,B5,B6(Body).001']} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['000000 & Metal (C2,T2).001']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['E2EBCA (B1,B4,B5,B6(BodyFrame)).001']} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials['18226AA (Number Plane).001']} />
        <mesh geometry={nodes.Cube001_4.geometry} material={materials['E2E2E2(B1~9(Body,Number)).001']} />
        <mesh geometry={nodes.Cube001_5.geometry} material={materials['DCE759 & Metal (DEVName, Statue).001']} />
        <mesh geometry={nodes.Cube001_6.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane).001']} />
        <mesh geometry={nodes.Cube001_7.geometry} material={materials['C0E8F6 (B1~9(Window)).001']} />
        <mesh geometry={nodes.Cube001_8.geometry} material={materials['D2D2D2 & Metal (B4,B5,B6,B7).001']} />
        <mesh geometry={nodes.Cube001_9.geometry} material={materials['23683C (RoofTop).001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/B6.glb')
