/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 B7_Enter2.glb -o B7_Enter2.jsx 
*/

import { useBox } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'
import React, { useEffect } from 'react'

export function B7_Enter2({position, ...props}) {
  const { scene, nodes, materials } = useGLTF('/assets/models/B7_Enter2.glb')
  const [meshRef, api] = useBox(() => ({
    args: [15, 14, 150],
    type: 'Static',
    mass: 1,
    position,
    ...props
  }))

  useEffect(() => {
    scene.traverse((obj) => {
      if(obj.isObject3D) {
        console.log(obj)
        obj.castShadow = true
        obj.receiveShadow = true
      }
    })
  }, [scene])

  return (
    <group ref={meshRef}>
      <group position={[80,-85,0]} rotation={[0,0,0]} scale={[3.242, 3.242, 4.501]}>
        <mesh geometry={nodes.Text007.geometry} material={materials['E2E2E2(B1~9(Body,Number)).001']} />
        <mesh geometry={nodes.Text007_1.geometry} material={materials['E2EBCA (B1,B4,B5,B6(BodyFrame)).001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/B7_Enter2.glb')
