/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 B7_EnterBlock.glb -o B7_EnterBlock.jsx 
*/

import { useBox } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'
import React, { useEffect } from 'react'

export function B7_EnterBlock({position, ...props}) {
  const { scene, nodes, materials } = useGLTF('/assets/models/B7_EnterBlock.glb')
  const [meshRef, api] = useBox(() => ({
    args: [18, 200, 200],
    type: 'Static',
    mass: 1,
    position,
    ...props
  }))

  useEffect(() => {
    scene.traverse((obj) => {
      if(obj.isObject3D) {
        console.log(obj)
        obj.castShadow = true
        obj.receiveShadow = true
      }
    })
  }, [scene])

  return (
    <group ref={meshRef}>
      <mesh geometry={nodes.B7_EnterBlock.geometry} material={materials['E2E2E2(B1~9(Body,Number)).001']} position={[65,0,0]} rotation={[0,0,0]} scale={[3.242, 3.242, 4.501]} />
    </group>
  )
}

useGLTF.preload('/assets/models/B7_EnterBlock.glb')
