/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 B8Pipe_R.glb -o B8Pipe_R.jsx 
*/

import { useBox } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'
import React, { useEffect } from 'react'


export function B8Pipe_R({position, ...props}) {
  const { scene, nodes, materials } = useGLTF('/assets/models/B8Pipe_R.glb')
  const [meshRef, api] = useBox(() => ({
    args: [5, 30, 7],
    type: 'Static',
    mass: 1,
    position,
    ...props
  }))

  useEffect(() => {
    scene.traverse((obj) => {
      if(obj.isObject3D) {
        console.log(obj)
        obj.castShadow = true
        obj.receiveShadow = true
      }
    })
  }, [scene])

  return (
    <group ref={meshRef}>
      <mesh geometry={nodes.B8Pipe_R.geometry} material={materials['E2E2E2(B1~9(Body,Number))']} position={[0,0,0]} rotation={[0,0,0]} scale={[4.452, 15, 4.429]} />
    </group>
  )
}

useGLTF.preload('/B8Pipe_R.glb')
