/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 B9-Pipe_R.glb -o B9-Pipe_R.jsx 
*/

import { useBox } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'
import React, { useEffect } from 'react'

export function B9_Pipe_R({position, ...props}) {
  const { scene, nodes, materials } = useGLTF('/assets/models/B9-Pipe_R.glb')
  const [meshRef, api] = useBox(() => ({
    args: [50, 220, 5],
    type: 'Static',
    mass: 1,
    position,
    ...props
  }))

  useEffect(() => {
    scene.traverse((obj) => {
      if(obj.isObject3D) {
        console.log(obj)
        obj.castShadow = true
        obj.receiveShadow = true
      }
    })
  }, [scene])

  return (
    <group ref={meshRef}>
      <mesh geometry={nodes['B9-Pipe_R'].geometry} material={materials['E2E2E2(B1~9(Body,Number))']} position={[5,0,0]} rotation={[0,0,0]} scale={[39.404, 65, 60.498]} />
    </group>
  )
}

useGLTF.preload('/assets/models/B9-Pipe_R.glb')
