/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 B9.glb -o B9.jsx 
*/
import { useBox } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'
import React, { useEffect } from 'react'

export function B9({position, ...props}) {
  const { scene, nodes, materials } = useGLTF('/assets/models/B9.glb')
  const [meshRef, api] = useBox(() => ({
    args: [75, 140, 110],
    type: 'Static',
    mass: 1,
    position,
    ...props
  }))

  useEffect(() => {
    scene.traverse((obj) => {
      if(obj.isObject3D) {
        console.log(obj)
        obj.castShadow = true
        obj.receiveShadow = true
      }
    })
  }, [scene])

  return (
    <group ref={meshRef}>
      <group position={[5,0,0]} rotation={[0,0,0]} scale={[39.404, 65, 60.498]}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane)']} />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['E2E2E2(B1~9(Body,Number))']} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['2F0708 (B4,B8,B9(Window Frame),T2(Table))']} />
        <mesh geometry={nodes.Cylinder001_3.geometry} material={materials['C0E8F6 (B1~9(Window))']} />
        <mesh geometry={nodes.Cylinder001_4.geometry} material={materials['D2D2D2 & Metal (B4,B5,B6,B7)']} />
        <mesh geometry={nodes.Cylinder001_5.geometry} material={materials['18226AA (Number Plane)']} />
        <mesh geometry={nodes.Cylinder001_6.geometry} material={materials['YuhanLogo(B9, Kiosk)']} />
        <mesh geometry={nodes.Cylinder001_7.geometry} material={materials['000000 & Metal (C2,T2)']} />
        <mesh geometry={nodes.Cylinder001_8.geometry} material={materials['AF9562 (C2)']} />
        <mesh geometry={nodes.Cylinder001_9.geometry} material={materials['DCE759 & Metal (DEVName, Statue).001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/B9.glb')
