/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 BusStation2.glb -o BusStation2.jsx 
*/

import { useBox } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'
import React, { useEffect } from 'react'

export function BusStation2({position, ...props}) {
  const { scene, nodes, materials } = useGLTF('/assets/models/BusStation2.glb')
  const [meshRef, api] = useBox(() => ({
    args: [8, 20, 34],
    type: 'Static',
    mass: 1,
    position,
    ...props
  }))

  useEffect(() => {
    scene.traverse((obj) => {
      if(obj.isObject3D) {
        console.log(obj)
        obj.castShadow = true
        obj.receiveShadow = true
      }
    })
  }, [scene])

  return (
    <group ref={meshRef}>
      <group position={[-3,0,0]} rotation={[0,0,0]} scale={[0.719, 7.5, 3.99]}>
        <mesh geometry={nodes.Cube038.geometry} material={materials['C0E8F6 (B1~9(Window))']} />
        <mesh geometry={nodes.Cube038_1.geometry} material={materials['373737 (BusStaion)']} />
        <mesh geometry={nodes.Cube038_2.geometry} material={nodes.Cube038_2.material} />
        <mesh geometry={nodes.Cube038_3.geometry} material={materials['FFFFFF (Number, BaskitBall)']} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/BusStation2.glb')
