/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 GrassAndTree2.glb -o GrassAndTree2.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/GrassAndTree2.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-246.074, 2.099, -177.916]} rotation={[Math.PI, 0, Math.PI]} scale={[12.72, 2.183, 47.147]}>
        <mesh geometry={nodes.Cube002.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane)']} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials['644F1C (Park Plane)']} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials['0CFF0F(Leaf,Smoking Booth)']} />
        <mesh geometry={nodes.Cube002_3.geometry} material={materials['0EA6EF (Leaf, Smoking Booth)']} />
        <mesh geometry={nodes.Cube002_4.geometry} material={materials['006400 (Leaf)']} />
        <mesh geometry={nodes.Cube002_5.geometry} material={materials['654321 (Wood)']} />
      </group>
    </group>
  )
}

useGLTF.preload('/GrassAndTree2.glb')
