/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Park1_B2.glb -o Park1_B2.jsx 
*/

import { useBox } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'
import React, { useEffect } from 'react'

export function Park1_B2({position, ...props}) {
  const { scene, nodes, materials } = useGLTF('/assets/models/Park1_B2.glb')
  const [meshRef, api] = useBox(() => ({
    args: [2, 50, 2],
    type: 'Static',
    mass: 1,
    position,
    ...props
  }))

  useEffect(() => {
    scene.traverse((obj) => {
      if(obj.isObject3D) {
        console.log(obj)
        obj.castShadow = true
        obj.receiveShadow = true
      }
    })
  }, [scene])

  return (
    <group ref={meshRef}>
      <group position={[12, 17.393, 12]} scale={61.994}>
        <mesh geometry={nodes.Plane009.geometry} material={materials['E71512 (Flower, BaskiBall, Smoking Booth)']} />
        <mesh geometry={nodes.Plane009_1.geometry} material={materials['FFFFFF (Number, BaskitBall)']} />
        <mesh geometry={nodes.Plane009_2.geometry} material={materials['E71512 (Flower, BaskiBall, Smoking Booth)']} />
        <mesh geometry={nodes.Plane009_3.geometry} material={materials['E71512 (Flower, BaskiBall, Smoking Booth)']} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/Park1_B2.glb')
