/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Park2_T2.glb -o Park2_T2.jsx 
*/


import { useBox } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'
import React, { useEffect } from 'react'

export function Park2_T2({position, ...props}) {
  const { scene, nodes, materials } = useGLTF('/assets/models/Park2_T2.glb')
  const [meshRef, api] = useBox(() => ({
    args: [9, 50, 9],
    type: 'Static',
    mass: 1,
    position,
    ...props
  }))

  useEffect(() => {
    scene.traverse((obj) => {
      if(obj.isObject3D) {
        console.log(obj)
        obj.castShadow = true
        obj.receiveShadow = true
      }
    })
  }, [scene])

  return (
    <group ref={meshRef}>
      <group position={[-2,0,-2]} scale={[-71.906, -42.936, -48.895]}>
        <mesh geometry={nodes.Plane002.geometry} material={materials['0CFF0F(Leaf,Smoking Booth)']} />
        <mesh geometry={nodes.Plane002_1.geometry} material={materials['654321 (Wood)']} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/Park2_T2.glb')
