/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Park1.glb -o Park1.jsx 
*/

import { useBox } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'
import React, { useEffect } from 'react'

export function Park1({position, ...props}) {
  const { scene, nodes, materials } = useGLTF('/assets/models/Park1.glb')
  const [meshRef, api] = useBox(() => ({
    args: [150, 1, 105],
    type: 'Static',
    mass: 1,
    position,
    ...props
  }))

  useEffect(() => {
    scene.traverse((obj) => {
      if(obj.isObject3D) {
        console.log(obj)
        obj.castShadow = true
        obj.receiveShadow = true
      }
    })
  }, [scene])

  return (
    <group ref={meshRef}>
      <group position={[29, 17.393, -22]} scale={61.994}>
        <mesh geometry={nodes.Plane190.geometry} material={materials['FFFFFF (Number, BaskitBall)']} />
        <mesh geometry={nodes.Plane190_1.geometry} material={materials['23683C (RoofTop)']} />
        <mesh geometry={nodes.Plane190_2.geometry} material={materials['E71512 (Flower, BaskiBall, Smoking Booth)']} />
        <mesh geometry={nodes.Plane190_3.geometry} material={materials['8F8E6E (Park)']} />
        <mesh geometry={nodes.Plane190_4.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane)']} />
        <mesh geometry={nodes.Plane190_5.geometry} material={materials['596054 (Park)']} />
        <mesh geometry={nodes.Plane190_6.geometry} material={materials['644F1C (Park Plane)']} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/Park1.glb')
