/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Park1_T7.glb -o Park1_T7.jsx 
*/

import { useBox } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'
import React, { useEffect } from 'react'

export function Park1_T7({position, ...props}) {
  const { scene, nodes, materials } = useGLTF('/assets/models/Park1_T7.glb')
  const [meshRef, api] = useBox(() => ({
    args: [4, 100, 4],
    type: 'Static',
    mass: 1,
    position,
    ...props
  }))

  useEffect(() => {
    scene.traverse((obj) => {
      if(obj.isObject3D) {
        console.log(obj)
        obj.castShadow = true
        obj.receiveShadow = true
      }
    })
  }, [scene])

  return (
    <group ref={meshRef}>
      <group position={[30, 17.393, -19.5]} scale={61.994}>
        <mesh geometry={nodes.Plane007.geometry} material={materials['006400 (Leaf)']} />
        <mesh geometry={nodes.Plane007_1.geometry} material={materials['654321 (Wood)']} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/Park1_T7.glb')
