/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Park2_T4.glb -o Park2_T4.jsx 
*/

import { useBox } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'
import React, { useEffect } from 'react'

export function Park2_T4({position, ...props}) {
  const { scene, nodes, materials } = useGLTF('/assets/models/Park2_T4.glb')
  const [meshRef, api] = useBox(() => ({
    args: [10, 100, 10],
    type: 'Static',
    mass: 1,
    position,
    ...props
  }))

  useEffect(() => {
    scene.traverse((obj) => {
      if(obj.isObject3D) {
        console.log(obj)
        obj.castShadow = true
        obj.receiveShadow = true
      }
    })
  }, [scene])

  return (
    <group ref={meshRef}>
      <group position={[2,0,2]} scale={[-71.906, -42.936, -48.895]}>
        <mesh geometry={nodes.Plane004.geometry} material={materials['654321 (Wood)']} />
        <mesh geometry={nodes.Plane004_1.geometry} material={materials['006400 (Leaf)']} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/Park2_T4.glb')
