/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Park2_T7.glb -o Park2_T7.jsx 
*/

import { useBox } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'
import React, { useEffect } from 'react'

export function Park2_T7({position, ...props}) {
  const { scene, nodes, materials } = useGLTF('/assets/models/Park2_T7.glb')
  const [meshRef, api] = useBox(() => ({
    args: [7, 70, 7],
    type: 'Static',
    mass: 1,
    position,
    ...props
  }))

  useEffect(() => {
    scene.traverse((obj) => {
      if(obj.isObject3D) {
        console.log(obj)
        obj.castShadow = true
        obj.receiveShadow = true
      }
    })
  }, [scene])

  return (
    <group ref={meshRef}>
      <group position={[-6,0,2.5]} scale={[-71.906, -42.936, -48.895]}>
        <mesh geometry={nodes.Plane007.geometry} material={materials['006400 (Leaf)']} />
        <mesh geometry={nodes.Plane007_1.geometry} material={materials['654321 (Wood)']} />
        <mesh geometry={nodes.Plane007_2.geometry} material={materials['006400 (Leaf)']} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/Park2_T7.glb')
