/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Park1_T1.glb -o Park1_T1.jsx 
*/

import { useBox } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'
import React, { useEffect } from 'react'

export function Park1_T1({position, ...props}) {
  const { scene, nodes, materials } = useGLTF('/assets/models/Park1_T1.glb')
  const [meshRef, api] = useBox(() => ({
    args: [8, 100, 10],
    type: 'Static',
    mass: 1,
    position,
    ...props
  }))

  useEffect(() => {
    scene.traverse((obj) => {
      if(obj.isObject3D) {
        console.log(obj)
        obj.castShadow = true
        obj.receiveShadow = true
      }
    })
  }, [scene])

  return (
    <group ref={meshRef}>
      <group position={[74.5, 17.393, 7.5]} scale={61.994}>
        <mesh geometry={nodes.Plane001.geometry} material={materials['006400 (Leaf)']} />
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['006400 (Leaf)']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials['654321 (Wood)']} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/Park1_T1.glb')
