/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 SideWalk-T.glb -o SideWalk_T.jsx 
*/

import { useBox } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'
import React, { useEffect } from 'react'

export function SideWalk_T2({position, ...props}) {
  const { scene, nodes, materials } = useGLTF('/assets/models/SideWalk-T.glb')
  const [meshRef, api] = useBox(() => ({
    args: [4, 50, 4],
    type: 'Static',
    mass: 1,
    position,
    ...props
  }))

  useEffect(() => {
    scene.traverse((obj) => {
      if(obj.isObject3D) {
        console.log(obj)
        obj.castShadow = true
        obj.receiveShadow = true
      }
    })
  }, [scene])

  return (
    <group ref={meshRef}>
      <group position={[0,0,0]} scale={[8.474, 10.505, 7.017]}>
        <mesh geometry={nodes.Cylinder018.geometry} material={materials['006400 (Leaf)']} />
        <mesh geometry={nodes.Cylinder018_1.geometry} material={materials['654321 (Wood)']} />
        <mesh geometry={nodes.Cylinder018_2.geometry} material={materials['644F1C (Park Plane)']} />
        <mesh geometry={nodes.Cylinder018_3.geometry} material={materials['AAAAAA (B8)']} />
        <mesh geometry={nodes.Cylinder018_4.geometry} material={materials['96947D(B2(Window Frame),B6(Stone))']} />
      </group>
    </group>
  )
}

useGLTF.preload('/SideWalk-T.glb')
