/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 SideWalk.glb -o SideWalk.jsx 
*/

import { useBox } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'
import React, { useEffect } from 'react'

export function SideWalk({position, ...props}) {
  const { scene, nodes, materials } = useGLTF('/assets/models/SideWalk.glb')
  const [meshRef, api] = useBox(() => ({
    args: [0, 0, 0],
    type: 'Static',
    mass: 1,
    position,
    ...props
  }))

  useEffect(() => {
    scene.traverse((obj) => {
      if(obj.isObject3D) {
        console.log(obj)
        obj.castShadow = true
        obj.receiveShadow = true
      }
    })
  }, [scene])

  return (
    <group ref={meshRef}>
      <group position={[69.747, 0, -197,783]} scale={[9.444, 0.001, 75]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane).003']} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['E77759 (SideWalk).001']} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials['654321 (Wood).002']} />
        <mesh geometry={nodes.Cube003_3.geometry} material={materials['FFFFFF (Number, BaskitBall).002']} />
        <mesh geometry={nodes.Cube003_4.geometry} material={materials['644F1C (Park Plane)']} />
        <mesh geometry={nodes.Cube003_5.geometry} material={materials['AAAAAA (B8)']} />
        <mesh geometry={nodes.Cube003_6.geometry} material={materials['96947D(B2(Window Frame),B6(Stone))']} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/SideWalk.glb')
