/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 SmokingArea.glb -o SmokingArea.jsx 
*/

import { useBox } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'
import React, { useEffect } from 'react'

export function SmokingArea({position, ...props}) {
  const { scene, nodes, materials } = useGLTF('/assets/models/SmokingArea.glb')
  const [meshRef, api] = useBox(() => ({
    args: [46, 40, 24],
    type: 'Static',
    mass: 1,
    position,
    ...props
  }))

  useEffect(() => {
    scene.traverse((obj) => {
      if(obj.isObject3D) {
        console.log(obj)
        obj.castShadow = true
        obj.receiveShadow = true
      }
    })
  }, [scene])

  return (
    <group ref={meshRef}>
      <group position={[0,0,0]} rotation={[0,0,0]} scale={[2.268, 18.224, 2.041]}>
        <mesh geometry={nodes.Pillar001.geometry} material={materials['654321 (Wood)']} />
        <mesh geometry={nodes.Pillar001_1.geometry} material={materials['774D15(SmokingBench)']} />
        <mesh geometry={nodes.Pillar001_2.geometry} material={materials['1760E7(Trashbaskit)']} />
        <mesh geometry={nodes.Pillar001_3.geometry} material={materials['33AF6A(Smoking Area RoofTop)']} />
        <mesh geometry={nodes.Pillar001_4.geometry} material={materials.smoking} />
        <mesh geometry={nodes.Pillar001_5.geometry} material={materials['8A4636 (Smoking Area)']} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/SmokingArea.glb')
