/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Wire_Netting.glb -o Wire_Netting.jsx 
*/

import { useBox } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'
import React, { useEffect } from 'react'

export function Wire_Netting({position, ...props}) {
  const { scene, nodes, materials } = useGLTF('/assets/models/Wire_netting.glb')
  const [meshRef, api] = useBox(() => ({
    args: [360, 2, 25],
    type: 'Static',
    mass: 1,
    position,
    ...props
  }))

  useEffect(() => {
    scene.traverse((obj) => {
      if(obj.isObject3D) {
        console.log(obj)
        obj.castShadow = true
        obj.receiveShadow = true
      }
    })
  }, [scene])

  return (
    <group ref={meshRef}>
      <mesh geometry={nodes.Wire_netting.geometry} material={materials['0CFF0F(Leaf,Smoking Booth).001']} position={[0,0,0]} rotation={[0,0,0]} scale={[7.5, 9.082, 9.947]} />
    </group>
  )
}

useGLTF.preload('/assets/models/Wire_netting.glb')
