/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 YuhanMap.glb -o YuhanMap.jsx 
*/

import { useGLTF } from '@react-three/drei'
import React, { useEffect } from 'react'
import { SkeletonUtils } from 'three-stdlib'

export function YuhanMap (props) {
  const { scene, nodes, materials } = useGLTF('/assets/models/YuhanMap.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
 
  useEffect(() => {
    scene.traverse((obj) => {
      if(obj.isObject3D) {
        // 
        obj.castShadow = true
        obj.receiveShadow = true
      }
    })
  }, [scene])

  return (
    <group {...props} dispose={null}>

      {/* <group position={[9.782, 20.316, -557.29]} scale={1.572}>
        <primitive object={nodes.Hip} />
        <primitive object={nodes.Thigh_L} />
        <primitive object={nodes.Thigh_R} />
        <primitive object={nodes.neutral_bone} />
        <skinnedMesh geometry={nodes.Cube007.geometry} material={materials['E7E500 & Metal (Statue)']} skeleton={nodes.Cube007.skeleton} />
        <skinnedMesh geometry={nodes.Cube007_1.geometry} material={materials['DCE759 & Metal (DEVName, Statue)']} skeleton={nodes.Cube007_1.skeleton} />
        <skinnedMesh geometry={nodes.Cube007_2.geometry} material={materials['96947D(B2(Window Frame),B6(Stone))']} skeleton={nodes.Cube007_2.skeleton} />
      </group> */}

      {/* 4호관 */}
      {/* <group position={[242.152, 55.009, 257.76]} rotation={[Math.PI, 0, Math.PI]} scale={[18.615, 4.051, 38.03]}>
        <mesh geometry={nodes.Cube359.geometry} material={materials['E2EBCA (B1,B4,B5,B6(BodyFrame))']} />
        <mesh geometry={nodes.Cube359_1.geometry} material={materials['858585 (B4,B9,B2)']} />
        <mesh geometry={nodes.Cube359_2.geometry} material={materials['D2D2D2 & Metal (B4,B5,B6,B7)']} />
        <mesh geometry={nodes.Cube359_3.geometry} material={materials['C0E8F6 (B1~9(Window))']} />
        <mesh geometry={nodes.Cube359_4.geometry} material={materials['2F0708 (B4,B8,B9(Window Frame),T2(Table))']} />
        <mesh geometry={nodes.Cube359_5.geometry} material={materials['4B1711 (Building4)']} />
        <mesh geometry={nodes.Cube359_6.geometry} material={materials['23683C (RoofTop)']} />
        <mesh geometry={nodes.Cube359_7.geometry} material={materials['DCE759 & Metal (DEVName, Statue)']} />
      </group> */}
      
      {/* 7호관 */}
      {/* <group position={[-344.578, 72.436, 189.311]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[3.242, 3.242, 4.501]}>
        <mesh geometry={nodes.Text008.geometry} material={materials['DCE759 & Metal (DEVName, Statue)']} />
        <mesh geometry={nodes.Text008_1.geometry} material={materials['C0E8F6 (B1~9(Window))']} />
        <mesh geometry={nodes.Text008_2.geometry} material={materials['18226AA (Number Plane)']} />
        <mesh geometry={nodes.Text008_3.geometry} material={materials['E2E2E2(B1~9(Body,Number))']} />
        <mesh geometry={nodes.Text008_4.geometry} material={materials['23683C (RoofTop)']} />
        <mesh geometry={nodes.Text008_5.geometry} material={materials['E2EBCA (B1,B4,B5,B6(BodyFrame))']} />
        <mesh geometry={nodes.Text008_6.geometry} material={materials['D2D2D2 & Metal (B4,B5,B6,B7)']} />
        <mesh geometry={nodes.Text008_7.geometry} material={materials['FFFFFF (Number, BaskitBall)']} />
        <mesh geometry={nodes.Text008_8.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane)']} />
        <mesh geometry={nodes.Text008_9.geometry} material={materials['644F1C (Park Plane)']} />
        <mesh geometry={nodes.Text008_10.geometry} material={materials['0CFF0F(Leaf,Smoking Booth)']} />
        <mesh geometry={nodes.Text008_11.geometry} material={materials['0EA6EF (Leaf, Smoking Booth)']} />
        <mesh geometry={nodes.Text008_12.geometry} material={materials['006400 (Leaf)']} />
        <mesh geometry={nodes.Text008_13.geometry} material={materials['654321 (Wood)']} />
      </group> */}

      {/* 흡연부스 */}
      {/* <group position={[131.979, 13.277, -125.014]} scale={[10.993, 9.714, 15.914]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials['0CFF0F(Leaf,Smoking Booth)']} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['C0E8F6 (B1~9(Window))']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['FFFFFF (Number, BaskitBall)']} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials['D2D2D2 & Metal (B4,B5,B6,B7)']} />
        <mesh geometry={nodes.Cube001_4.geometry} material={materials['006400 (Leaf)']} />
        <mesh geometry={nodes.Cube001_5.geometry} material={materials['2CC337 (Smoking Booth)']} />
        <mesh geometry={nodes.Cube001_6.geometry} material={materials['000000 (B1, B2, B9, Smoking Booth)']} />
        <mesh geometry={nodes.Cube001_7.geometry} material={materials['1760E7(Trashbaskit)']} />
        <mesh geometry={nodes.Cube001_8.geometry} material={materials['E7E541 (Smoking Booth)']} />
        <mesh geometry={nodes.Cube001_9.geometry} material={materials['0EA6EF (Leaf, Smoking Booth)']} />
        <mesh geometry={nodes.Cube001_10.geometry} material={materials['E71512 (Flower, BaskiBall, Smoking Booth)']} />
        <mesh geometry={nodes.Cube001_11.geometry} material={materials['TextTure (Smoking Booth)']} />
      </group> */}

      {/* 8호관 */}
      {/* <group position={[-380.008, 102.136, -176.308]} rotation={[-Math.PI, 0, -Math.PI]} scale={[4.452, 15, 4.429]}>
        <mesh geometry={nodes.실린더005.geometry} material={materials['E2E2E2(B1~9(Body,Number))']} />
        <mesh geometry={nodes.실린더005_1.geometry} material={materials['18226AA (Number Plane)']} />
        <mesh geometry={nodes.실린더005_2.geometry} material={materials['DCE759 & Metal (DEVName, Statue)']} />
        <mesh geometry={nodes.실린더005_3.geometry} material={materials['23683C (RoofTop)']} />
        <mesh geometry={nodes.실린더005_4.geometry} material={materials['2F0708 (B4,B8,B9(Window Frame),T2(Table))']} />
        <mesh geometry={nodes.실린더005_5.geometry} material={materials['D2D2D2 & Metal (B4,B5,B6,B7)']} />
        <mesh geometry={nodes.실린더005_6.geometry} material={materials['C0E8F6 (B1~9(Window))']} />
        <mesh geometry={nodes.실린더005_7.geometry} material={materials['AAAAAA (B8)']} />
        <mesh geometry={nodes.실린더005_8.geometry} material={materials['FFFFFF (Number, BaskitBall)']} />
        <mesh geometry={nodes.실린더005_9.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane)']} />
        <mesh geometry={nodes.실린더005_10.geometry} material={materials['644F1C (Park Plane)']} />
        <mesh geometry={nodes.실린더005_11.geometry} material={materials['0CFF0F(Leaf,Smoking Booth)']} />
        <mesh geometry={nodes.실린더005_12.geometry} material={materials['0EA6EF (Leaf, Smoking Booth)']} />
        <mesh geometry={nodes.실린더005_13.geometry} material={materials['006400 (Leaf)']} />
        <mesh geometry={nodes.실린더005_14.geometry} material={materials['654321 (Wood)']} />
      </group> */}

      {/* 9호관 */}
      {/* <group position={[262.607, 66.181, 40.988]} rotation={[Math.PI, 0, Math.PI]} scale={[39.404, 65, 60.498]}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane)']} />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['E2E2E2(B1~9(Body,Number))']} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['2F0708 (B4,B8,B9(Window Frame),T2(Table))']} />
        <mesh geometry={nodes.Cylinder001_3.geometry} material={materials['C0E8F6 (B1~9(Window))']} />
        <mesh geometry={nodes.Cylinder001_4.geometry} material={materials['D2D2D2 & Metal (B4,B5,B6,B7)']} />
        <mesh geometry={nodes.Cylinder001_5.geometry} material={materials['18226AA (Number Plane)']} />
        <mesh geometry={nodes.Cylinder001_6.geometry} material={materials['YuhanLogo(B9, Kiosk)']} />
        <mesh geometry={nodes.Cylinder001_7.geometry} material={materials['000000 & Metal (C2,T2)']} />
        <mesh geometry={nodes.Cylinder001_8.geometry} material={materials['AF9562 (C2)']} />
        <mesh geometry={nodes.Cylinder001_9.geometry} material={materials['DCE759 & Metal (DEVName, Statue)']} />
      </group> */}

      {/* 1호관9호관 사이 건물 */}
      {/* <group position={[226.55, 81.646, -29.232]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-25.054, -75.261, -13.44]}>
        <mesh geometry={nodes.Cube079.geometry} material={materials['858585 (B4,B9,B2)']} />
        <mesh geometry={nodes.Cube079_1.geometry} material={materials['FFFFFF (Number, BaskitBall)']} />
        <mesh geometry={nodes.Cube079_2.geometry} material={materials['E2EBCA (B1,B4,B5,B6(BodyFrame))']} />
        <mesh geometry={nodes.Cube079_3.geometry} material={materials['000000 & Metal (C2,T2)']} />
        <mesh geometry={nodes.Cube079_4.geometry} material={materials['AF9562 (C2)']} />
        <mesh geometry={nodes.Cube079_5.geometry} material={materials['2F0708 (B4,B8,B9(Window Frame),T2(Table))']} />
      </group> */}

      {/* 5호관 6호관 테라스건물 */}
      {/* <group position={[1.644, 12.767, 152.007]} scale={[0.253, 12, 3.955]}>
        <mesh geometry={nodes.Cube073.geometry} material={materials['C0E8F6 (B1~9(Window))']} />
        <mesh geometry={nodes.Cube073_1.geometry} material={materials['E2E2E2(B1~9(Body,Number))']} />
        <mesh geometry={nodes.Cube073_2.geometry} material={materials['D2D2D2 & Metal (B4,B5,B6,B7)']} />
        <mesh geometry={nodes.Cube073_3.geometry} material={materials['858585 (B4,B9,B2)']} />
      </group> */}

      {/* 2호관 */}
      {/* <group position={[217.926, 72.727, -196.58]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[2.57, 0.937, 4.787]}>
        <mesh geometry={nodes.Text001.geometry} material={materials['DCE759 & Metal (DEVName, Statue)']} />
        <mesh geometry={nodes.Text001_1.geometry} material={materials['D18A8D (B2)']} />
        <mesh geometry={nodes.Text001_2.geometry} material={materials['000000 & Metal (C2,T2)']} />
        <mesh geometry={nodes.Text001_3.geometry} material={materials['61544D (B1,B2,B5,B6(Body)']} />
        <mesh geometry={nodes.Text001_4.geometry} material={materials['3E3C3A (B2)']} />
        <mesh geometry={nodes.Text001_5.geometry} material={materials['FFFFFF (Number, BaskitBall)']} />
        <mesh geometry={nodes.Text001_6.geometry} material={materials['858585 (B4,B9,B2)']} />
        <mesh geometry={nodes.Text001_7.geometry} material={materials['23683C (RoofTop)']} />
        <mesh geometry={nodes.Text001_8.geometry} material={materials['E2EBCA (B1,B4,B5,B6(BodyFrame))']} />
        <mesh geometry={nodes.Text001_9.geometry} material={materials['C0E8F6 (B1~9(Window))']} />
        <mesh geometry={nodes.Text001_10.geometry} material={materials['96947D(B2(Window Frame),B6(Stone))']} />
        <mesh geometry={nodes.Text001_11.geometry} material={materials['E2E2E2(B1~9(Body,Number))']} />
        <mesh geometry={nodes.Text001_12.geometry} material={materials['YuhanLogo(B9, Kiosk)']} />
      </group> */}

      {/* 흡연구역 */}
      {/* <group position={[41.672, 23.001, -284.431]} rotation={[Math.PI, 0, 0]} scale={[2.268, 18.224, 2.041]}>
        <mesh geometry={nodes.Pillar001.geometry} material={materials['654321 (Wood)']} />
        <mesh geometry={nodes.Pillar001_1.geometry} material={materials['774D15(SmokingBench)']} />
        <mesh geometry={nodes.Pillar001_2.geometry} material={materials['1760E7(Trashbaskit)']} />
        <mesh geometry={nodes.Pillar001_3.geometry} material={materials['33AF6A(Smoking Area RoofTop)']} />
        <mesh geometry={nodes.Pillar001_4.geometry} material={materials.smoking} />
        <mesh geometry={nodes.Pillar001_5.geometry} material={materials['8A4636 (Smoking Area)']} />
      </group> */}

      {/* 1 2 3호관 공원 */}
      {/* <group position={[94.195, 17.393, -223.254]} scale={61.994}>
        <mesh geometry={nodes.Plane190.geometry} material={materials['FFFFFF (Number, BaskitBall)']} />
        <mesh geometry={nodes.Plane190_1.geometry} material={materials['23683C (RoofTop)']} />
        <mesh geometry={nodes.Plane190_2.geometry} material={materials['E71512 (Flower, BaskiBall, Smoking Booth)']} />
        <mesh geometry={nodes.Plane190_3.geometry} material={materials['FFFFFF (Number, BaskitBall)']} />
        <mesh geometry={nodes.Plane190_4.geometry} material={materials['E71512 (Flower, BaskiBall, Smoking Booth)']} />
        <mesh geometry={nodes.Plane190_5.geometry} material={materials['E71512 (Flower, BaskiBall, Smoking Booth)']} />
        <mesh geometry={nodes.Plane190_6.geometry} material={materials['8F8E6E (Park)']} />
        <mesh geometry={nodes.Plane190_7.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane)']} />
        <mesh geometry={nodes.Plane190_8.geometry} material={materials['596054 (Park)']} />
        <mesh geometry={nodes.Plane190_9.geometry} material={materials['006400 (Leaf)']} />
        <mesh geometry={nodes.Plane190_10.geometry} material={materials['654321 (Wood)']} />
        <mesh geometry={nodes.Plane190_11.geometry} material={materials['0CFF0F(Leaf,Smoking Booth)']} />
        <mesh geometry={nodes.Plane190_12.geometry} material={materials['654321 (Wood)']} />
        <mesh geometry={nodes.Plane190_13.geometry} material={materials['0EA6EF (Leaf, Smoking Booth)']} />
        <mesh geometry={nodes.Plane190_14.geometry} material={materials['006400 (Leaf)']} />
        <mesh geometry={nodes.Plane190_15.geometry} material={materials['644F1C (Park Plane)']} />
        <mesh geometry={nodes.Plane190_16.geometry} material={materials['654321 (Wood)']} />
      </group> */}
      
      {/* 7호관8호관 공원 */}
      {/* <group position={[-362.743, 22.281, 9.593]} scale={[-71.906, -42.936, -48.895]}>
        <mesh geometry={nodes.Plane009.geometry} material={materials['644F1C (Park Plane)']} />
        <mesh geometry={nodes.Plane009_1.geometry} material={materials['8F8E6E (Park)']} />
        <mesh geometry={nodes.Plane009_2.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane)']} />
        <mesh geometry={nodes.Plane009_3.geometry} material={materials['596054 (Park)']} />
        <mesh geometry={nodes.Plane009_4.geometry} material={materials['654321 (Wood)']} />
        <mesh geometry={nodes.Plane009_5.geometry} material={materials['006400 (Leaf)']} />
        <mesh geometry={nodes.Plane009_6.geometry} material={materials['0EA6EF (Leaf, Smoking Booth)']} />
        <mesh geometry={nodes.Plane009_7.geometry} material={materials['654321 (Wood)']} />
        <mesh geometry={nodes.Plane009_8.geometry} material={materials['0CFF0F(Leaf,Smoking Booth)']} />
        <mesh geometry={nodes.Plane009_9.geometry} material={materials['654321 (Wood)']} />
        <mesh geometry={nodes.Plane009_10.geometry} material={materials['006400 (Leaf)']} />
      </group> */}

      {/* 5호관 */}
      {/* <group position={[13.651, 77.182, 120.584]} rotation={[0, 1.571, 0]} scale={[25, 77.5, 120]}>
        <mesh geometry={nodes.Cube011.geometry} material={materials['61544D (B1,B2,B5,B6(Body)']} />
        <mesh geometry={nodes.Cube011_1.geometry} material={materials['000000 & Metal (C2,T2)']} />
        <mesh geometry={nodes.Cube011_2.geometry} material={materials['18226AA (Number Plane)']} />
        <mesh geometry={nodes.Cube011_3.geometry} material={materials['E2E2E2(B1~9(Body,Number))']} />
        <mesh geometry={nodes.Cube011_4.geometry} material={materials['DCE759 & Metal (DEVName, Statue)']} />
        <mesh geometry={nodes.Cube011_5.geometry} material={materials['E2EBCA (B1,B4,B5,B6(BodyFrame))']} />
        <mesh geometry={nodes.Cube011_6.geometry} material={materials['C0E8F6 (B1~9(Window))']} />
        <mesh geometry={nodes.Cube011_7.geometry} material={materials['D2D2D2 & Metal (B4,B5,B6,B7)']} />
        <mesh geometry={nodes.Cube011_8.geometry} material={materials['23683C (RoofTop)']} />
        <mesh geometry={nodes.Cube011_9.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane)']} />
        <mesh geometry={nodes.Cube011_10.geometry} material={materials['0EA6EF (Leaf, Smoking Booth)']} />
      </group> */}

      {/* 5호관 6호관 사이 큰건물 */}
      {/* <group position={[128.273, 86.249, 199.836]} rotation={[0, 0.384, 0]} scale={[0.353, 1.489, 3.966]}>
        <mesh geometry={nodes.Cube085.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane)']} />
        <mesh geometry={nodes.Cube085_1.geometry} material={materials['C0E8F6 (B1~9(Window))']} />
        <mesh geometry={nodes.Cube085_2.geometry} material={materials['E2EBCA (B1,B4,B5,B6(BodyFrame))']} />
      </group> */}

      {/* 6호관 */}
      {/* <group position={[12.86, 77.556, 275.937]} rotation={[0, -1.571, 0]} scale={[25, 77.5, 120]}>
        <mesh geometry={nodes.Cube119.geometry} material={materials['61544D (B1,B2,B5,B6(Body)']} />
        <mesh geometry={nodes.Cube119_1.geometry} material={materials['000000 & Metal (C2,T2)']} />
        <mesh geometry={nodes.Cube119_2.geometry} material={materials['E2EBCA (B1,B4,B5,B6(BodyFrame))']} />
        <mesh geometry={nodes.Cube119_3.geometry} material={materials['18226AA (Number Plane)']} />
        <mesh geometry={nodes.Cube119_4.geometry} material={materials['E2E2E2(B1~9(Body,Number))']} />
        <mesh geometry={nodes.Cube119_5.geometry} material={materials['DCE759 & Metal (DEVName, Statue)']} />
        <mesh geometry={nodes.Cube119_6.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane)']} />
        <mesh geometry={nodes.Cube119_7.geometry} material={materials['C0E8F6 (B1~9(Window))']} />
        <mesh geometry={nodes.Cube119_8.geometry} material={materials['D2D2D2 & Metal (B4,B5,B6,B7)']} />
        <mesh geometry={nodes.Cube119_9.geometry} material={materials['23683C (RoofTop)']} />
      </group> */}

      {/* 8호관기둥 */}
      {/* <mesh geometry={nodes.B8Pipe_R.geometry} material={materials['E2E2E2(B1~9(Body,Number))']} position={[-325.417, 15.065, -90.444]} rotation={[-Math.PI, 0, -Math.PI]} scale={[4.452, 15, 4.429]} />
      <mesh geometry={nodes.B8Pipe_L.geometry} material={materials['E2E2E2(B1~9(Body,Number))']} position={[-377.862, 15.065, -90.765]} rotation={[-Math.PI, 0, -Math.PI]} scale={[4.452, 15, 4.429]} /> */}

      {/* 3호관 */}
      {/* <group position={[-103.585, 72.171, -147.282]} rotation={[Math.PI / 2, 0, 0]} scale={[8.072, 8.072, 9.321]}>
        <mesh geometry={nodes.텍스트001.geometry} material={materials['DCE759 & Metal (DEVName, Statue)']} />
        <mesh geometry={nodes.텍스트001_1.geometry} material={materials['000000 (B1, B2, B9, Smoking Booth)']} />
        <mesh geometry={nodes.텍스트001_2.geometry} material={materials['E2EBCA (B1,B4,B5,B6(BodyFrame))']} />
        <mesh geometry={nodes.텍스트001_3.geometry} material={materials['C0E8F6 (B1~9(Window))']} />
        <mesh geometry={nodes.텍스트001_4.geometry} material={materials['18226AA (Number Plane)']} />
        <mesh geometry={nodes.텍스트001_5.geometry} material={materials['FFFFFF (Number, BaskitBall)']} />
        <mesh geometry={nodes.텍스트001_6.geometry} material={materials['61544D (B1,B2,B5,B6(Body)']} />
        <mesh geometry={nodes.텍스트001_7.geometry} material={materials['23683C (RoofTop)']} />
        <mesh geometry={nodes.텍스트001_8.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane).001']} />
        <mesh geometry={nodes.텍스트001_9.geometry} material={materials['0EA6EF (Leaf, Smoking Booth)']} />
        <mesh geometry={nodes.텍스트001_10.geometry} material={materials['644F1C (Park Plane)']} />
        <mesh geometry={nodes.텍스트001_11.geometry} material={materials['006400 (Leaf)']} />
        <mesh geometry={nodes.텍스트001_12.geometry} material={materials['006400 (Leaf)']} />
        <mesh geometry={nodes.텍스트001_13.geometry} material={materials['654321 (Wood)']} />
      </group> */}

      {/* 1호관 */}
      {/* <group position={[66.35, 84.082, -69.278]} rotation={[Math.PI / 2, 0, 0]} scale={[8.072, 8.072, 9.321]}>
        <mesh geometry={nodes.텍스트003.geometry} material={materials['DCE759 & Metal (DEVName, Statue).001']} />
        <mesh geometry={nodes.텍스트003_1.geometry} material={materials['000000 (B1, B2, B9, Smoking Booth).001']} />
        <mesh geometry={nodes.텍스트003_2.geometry} material={materials['E2EBCA (B1,B4,B5,B6(BodyFrame))']} />
        <mesh geometry={nodes.텍스트003_3.geometry} material={materials['C0E8F6 (B1~9(Window))']} />
        <mesh geometry={nodes.텍스트003_4.geometry} material={materials['FFFFFF (Number, BaskitBall)']} />
        <mesh geometry={nodes.텍스트003_5.geometry} material={materials['61544D (B1,B2,B5,B6(Body)']} />
        <mesh geometry={nodes.텍스트003_6.geometry} material={materials['23683C (RoofTop)']} />
        <mesh geometry={nodes.텍스트003_7.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane)']} />
        <mesh geometry={nodes.텍스트003_8.geometry} material={materials['0EA6EF (Leaf, Smoking Booth)']} />
      </group> */}
      
      {/* 2호관 입구 */}
      {/* <group position={[179.985, 75.604, -300.483]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[2.57, 0.937, 4.787]}>
        <mesh geometry={nodes.Text004.geometry} material={materials['D18A8D (B2)']} />
        <mesh geometry={nodes.Text004_1.geometry} material={materials['000000 & Metal (C2,T2)']} />
        <mesh geometry={nodes.Text004_2.geometry} material={materials['3E3C3A (B2)']} />
        <mesh geometry={nodes.Text004_3.geometry} material={materials['FFFFFF (Number, BaskitBall)']} />
        <mesh geometry={nodes.Text004_4.geometry} material={materials['C0E8F6 (B1~9(Window))']} />
        <mesh geometry={nodes.Text004_5.geometry} material={materials['96947D(B2(Window Frame),B6(Stone))']} />
        <mesh geometry={nodes.Text004_6.geometry} material={materials['E2E2E2(B1~9(Body,Number))']} />
        <mesh geometry={nodes.Text004_7.geometry} material={materials['YuhanLogo(B9, Kiosk)']} />
      </group> */}
      
      {/* 5호관 기둥건물(바깥) */}
      {/* <group position={[-67.348, 78.431, 165.355]} rotation={[0, 1.571, 0]} scale={[25, 77.5, 120]}>
        <mesh geometry={nodes.Cube002.geometry} material={materials['61544D (B1,B2,B5,B6(Body)']} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials['E2EBCA (B1,B4,B5,B6(BodyFrame))']} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials['C0E8F6 (B1~9(Window))']} />
        <mesh geometry={nodes.Cube002_3.geometry} material={materials['23683C (RoofTop)']} />
      </group> */}

      {/* 5호관 기둥건물(안쪽) */}
      {/* <group position={[83.496, 84.734, 165.022]} rotation={[0, 1.571, 0]} scale={[25, 77.5, 120]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials['61544D (B1,B2,B5,B6(Body)']} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials['E2EBCA (B1,B4,B5,B6(BodyFrame))']} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials['C0E8F6 (B1~9(Window))']} />
        <mesh geometry={nodes.Cube004_3.geometry} material={materials['23683C (RoofTop)']} />
      </group> */}
      
      {/* 6호관 기둥건물 */}
      {/* <group position={[12.736, 85.407, 232.529]} rotation={[0, -1.571, 0]} scale={[25, 77.5, 120]}>
        <mesh geometry={nodes.Cube005.geometry} material={materials['61544D (B1,B2,B5,B6(Body)']} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials['E2EBCA (B1,B4,B5,B6(BodyFrame))']} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials['C0E8F6 (B1~9(Window))']} />
      </group> */}

      {/* <mesh geometry={nodes.B9Enter.geometry} material={materials['858585 (B4,B9,B2)']} position={[229.787, 0.408, 46.393]} rotation={[Math.PI, 0, Math.PI]} scale={[39.404, 65, 60.498]} />

      <mesh geometry={nodes['B9-Pipe_R'].geometry} material={materials['E2E2E2(B1~9(Body,Number))']} position={[200.264, 30.402, 61.894]} rotation={[Math.PI, 0, Math.PI]} scale={[39.404, 65, 60.498]} />
      
      <mesh geometry={nodes['B9-Pipe_L'].geometry} material={materials['E2E2E2(B1~9(Body,Number))']} position={[200.264, 30.402, 20.396]} rotation={[Math.PI, 0, Math.PI]} scale={[39.404, 65, 60.498]} /> */}

      {/* 4호관 식당 */}
      {/* <group position={[211.596, 24.087, 308.403]} rotation={[Math.PI, 0, Math.PI]} scale={[18.615, 4.051, 38.03]}>
        <mesh geometry={nodes.Cube006.geometry} material={materials['E2EBCA (B1,B4,B5,B6(BodyFrame))']} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials['858585 (B4,B9,B2)']} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['D2D2D2 & Metal (B4,B5,B6,B7)']} />
        <mesh geometry={nodes.Cube006_3.geometry} material={materials['C0E8F6 (B1~9(Window))']} />
        <mesh geometry={nodes.Cube006_4.geometry} material={materials['2F0708 (B4,B8,B9(Window Frame),T2(Table))']} />
        <mesh geometry={nodes.Cube006_5.geometry} material={materials['4B1711 (Building4)']} />
      </group> */}

      {/* 4호관 입구 */}
      {/* <group position={[220.784, 29.761, 182.633]} rotation={[Math.PI, 0, Math.PI]} scale={[18.615, 4.051, 38.03]}>cd 
        <mesh geometry={nodes.Cube008.geometry} material={materials['E2EBCA (B1,B4,B5,B6(BodyFrame))']} />
        <mesh geometry={nodes.Cube008_1.geometry} material={materials['858585 (B4,B9,B2)']} />
        <mesh geometry={nodes.Cube008_2.geometry} material={materials['D2D2D2 & Metal (B4,B5,B6,B7)']} />
        <mesh geometry={nodes.Cube008_3.geometry} material={materials['C0E8F6 (B1~9(Window))']} />
        <mesh geometry={nodes.Cube008_4.geometry} material={materials['2F0708 (B4,B8,B9(Window Frame),T2(Table))']} />
        <mesh geometry={nodes.Cube008_5.geometry} material={materials['18226AA (Number Plane)']} />
      </group> */}
      
      {/* 4호관 오르막 */}
      {/* <mesh geometry={nodes.B4Enter2.geometry} material={materials['858585 (B4,B9,B2)']} position={[225.212, 0.848, 129.039]} rotation={[Math.PI, 0, Math.PI]} scale={[18.615, 4.051, 38.03]} /> */}

      {/* 버스정류장 (바깥) */}
      {/* <group position={[526.536, 9.408, -235.881]} rotation={[Math.PI, 0, Math.PI]} scale={[0.719, 7.5, 3.99]}>
        <mesh geometry={nodes.Cube038.geometry} material={materials['C0E8F6 (B1~9(Window))']} />
        <mesh geometry={nodes.Cube038_1.geometry} material={materials['373737 (BusStaion)']} />
        <mesh geometry={nodes.Cube038_2.geometry} material={nodes.Cube038_2.material} />
        <mesh geometry={nodes.Cube038_3.geometry} material={materials['FFFFFF (Number, BaskitBall)']} />
      </group> */}

      {/* 버스정류장 (안쪽) */}
      {/* <group position={[271.453, 9.959, -163.289]} scale={[1.027, 6.844, 6.844]}>
        <mesh geometry={nodes.Cube057.geometry} material={materials['373737 (BusStaion)']} />
        <mesh geometry={nodes.Cube057_1.geometry} material={materials['373737 (BusStaion)']} />
        <mesh geometry={nodes.Cube057_2.geometry} material={materials['FFFFFF (Number, BaskitBall)']} />
        <mesh geometry={nodes.Cube057_3.geometry} material={materials['1760E7(Trashbaskit)']} />
        <mesh geometry={nodes.Cube057_4.geometry} material={materials['E71512 (Flower, BaskiBall, Smoking Booth)']} />
        <mesh geometry={nodes.Cube057_5.geometry} material={materials['FFFFFF (Number, BaskitBall)']} />
        <mesh geometry={nodes.Cube057_6.geometry} material={materials['C0E8F6 (B1~9(Window))']} />
      </group> */}
      
      {/* 흡연부스 */}
      {/* <mesh geometry={nodes.Wire_netting.geometry} material={materials['0CFF0F(Leaf,Smoking Booth)']} position={[50.639, 10.339, 395.918]} rotation={[Math.PI / 2, 0, 0]} scale={[7.5, 9.082, 9.947]} />
       */}
      {/* 입구 왼쪽 */}
      {/* <mesh geometry={nodes.Enter_L.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane)']} position={[227.941, 36.653, -387.413]} scale={[8.47, 22.599, 8.47]} /> */}

      {/* 입구 오른쪽 */}
      {/* <mesh geometry={nodes.Enter_R.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane)']} position={[225.126, 36.653, -511.304]} rotation={[Math.PI, 0, Math.PI]} scale={[8.47, 22.599, 8.47]} /> */}

      {/* 인도 */}
      {/* <group position={[126.747, -0.139, 70.783]} scale={[9.444, 0.001, 75]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane).001']} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['E77759 (SideWalk).001']} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials['654321 (Wood).001']} />
        <mesh geometry={nodes.Cube003_3.geometry} material={materials['FFFFFF (Number, BaskitBall).001']} />
        <mesh geometry={nodes.Cube003_4.geometry} material={materials['644F1C (Park Plane)']} />
        <mesh geometry={nodes.Cube003_5.geometry} material={materials['AAAAAA (B8)']} />
        <mesh geometry={nodes.Cube003_6.geometry} material={materials['96947D(B2(Window Frame),B6(Stone))']} />
      </group> */}

      {/* 5호관5호관테라스책상의자2-1 */}
      {/* <group position={[-68.087, 7.741, 200.422]} scale={[0.25, 0.25, 3.25]}>
        <mesh geometry={nodes.Cube018.geometry} material={materials['000000 & Metal (C2,T2)']} />
        <mesh geometry={nodes.Cube018_1.geometry} material={materials['AF9562 (C2)']} />
        <mesh geometry={nodes.Cube018_2.geometry} material={materials['2F0708 (B4,B8,B9(Window Frame),T2(Table))']} />
      </group> */}

      {/* 5호관5호관테라스책상의자2-2 */}
      {/* <group position={[-68.087, 7.741, 231.193]} rotation={[Math.PI, 0, Math.PI]} scale={[0.25, 0.25, 3.25]}>
        <mesh geometry={nodes.Cube027.geometry} material={materials['000000 & Metal (C2,T2)']} />
        <mesh geometry={nodes.Cube027_1.geometry} material={materials['AF9562 (C2)']} />
        <mesh geometry={nodes.Cube027_2.geometry} material={materials['2F0708 (B4,B8,B9(Window Frame),T2(Table))']} />
      </group> */}

      {/* 5호관5호관테라스책상의자1-1 */}
      {/* <group position={[-37.949, 8.666, 160.576]} scale={[0.25, 3.25, 0.25]}>
        <mesh geometry={nodes.Cube010.geometry} material={materials['D2D2D2 & Metal (B4,B5,B6,B7)']} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['455A33(T1)']} />
      </group> */}

      {/* 5호관5호관테라스책상의자1-2 */}
      {/* <group position={[-37.949, 8.666, 186.617]} scale={[0.25, 3.25, 0.25]}>
        <mesh geometry={nodes.Cube052.geometry} material={materials['D2D2D2 & Metal (B4,B5,B6,B7)']} />
        <mesh geometry={nodes.Cube052_1.geometry} material={materials['455A33(T1)']} />
      </group> */}

      {/* 5호관5호관테라스책상의자1-3 */}
      {/* <group position={[-24.238, 8.666, 160.576]} scale={[0.25, 3.25, 0.25]}>
        <mesh geometry={nodes.Cube040.geometry} material={materials['D2D2D2 & Metal (B4,B5,B6,B7)']} />
        <mesh geometry={nodes.Cube040_1.geometry} material={materials['455A33(T1)']} />
      </group> */}

      {/* 5호관5호관테라스책상의자1-4 */}
      {/* <group position={[-24.238, 8.666, 186.617]} scale={[0.25, 3.25, 0.25]}>
        <mesh geometry={nodes.Cube055.geometry} material={materials['D2D2D2 & Metal (B4,B5,B6,B7)']} />
        <mesh geometry={nodes.Cube055_1.geometry} material={materials['455A33(T1)']} />
      </group> */}

      {/* 5호관5호관테라스책상의자1-5 */}
      {/* <group position={[-11.374, 8.666, 160.576]} scale={[0.25, 3.25, 0.25]}>
        <mesh geometry={nodes.Cube043.geometry} material={materials['D2D2D2 & Metal (B4,B5,B6,B7)']} />
        <mesh geometry={nodes.Cube043_1.geometry} material={materials['455A33(T1)']} />
      </group> */}

      {/* 5호관5호관테라스책상의자1-6 */}
      {/* <group position={[-11.374, 8.666, 186.617]} scale={[0.25, 3.25, 0.25]}>
        <mesh geometry={nodes.Cube058.geometry} material={materials['D2D2D2 & Metal (B4,B5,B6,B7)']} />
        <mesh geometry={nodes.Cube058_1.geometry} material={materials['455A33(T1)']} />
      </group> */}

      {/* 인도 나무 1 */}
      {/* <group position={[-91.358, 4.475, -7.105]} scale={[8.474, 10.505, 7.017]}>
        <mesh geometry={nodes.Cylinder018.geometry} material={materials['006400 (Leaf)']} />
        <mesh geometry={nodes.Cylinder018_1.geometry} material={materials['654321 (Wood)']} />
      </group> */}

      {/* 인도 나무 2 */}
      {/* <group position={[-3.355, 4.438, -7.105]} scale={[8.474, 10.505, 7.017]}>
        <mesh geometry={nodes.Cylinder016.geometry} material={materials['006400 (Leaf)']} />
        <mesh geometry={nodes.Cylinder016_1.geometry} material={materials['654321 (Wood)']} />
      </group> */}

      {/* 인도 나무 3 */}
      {/* <group position={[112.294, 4.438, -7.105]} scale={[8.474, 10.505, 7.017]}>
        <mesh geometry={nodes.Cylinder003.geometry} material={materials['006400 (Leaf)']} />
        <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['654321 (Wood)']} />
      </group> */}

      {/* 흡연부스 큰나무 */}
      {/* <group position={[69.012, 2.099, -324.727]} rotation={[0, Math.PI / 2, 0]} scale={[12.72, 2.183, 87.156]}>
        <mesh geometry={nodes.Cube013.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane)']} />
        <mesh geometry={nodes.Cube013_1.geometry} material={materials['644F1C (Park Plane)']} />
        <mesh geometry={nodes.Cube013_2.geometry} material={materials['0CFF0F(Leaf,Smoking Booth)']} />
        <mesh geometry={nodes.Cube013_3.geometry} material={materials['0EA6EF (Leaf, Smoking Booth)']} />
        <mesh geometry={nodes.Cube013_4.geometry} material={materials['006400 (Leaf)']} />
        <mesh geometry={nodes.Cube013_5.geometry} material={materials['654321 (Wood)']} />
      </group> */}

      {/* 키오스크 1호관 */}
      {/* <group position={[37.031, 7.1, -18.57]} rotation={[Math.PI / 2, 0, 0]} scale={0.766}>
        <mesh geometry={nodes.Empty001.geometry} material={materials['YuhanLogo(B9, Kiosk)']} />
        <mesh geometry={nodes.Empty001_1.geometry} material={materials['D7EFD4 (Kiosk)']} />
        <mesh geometry={nodes.Empty001_2.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane)']} />
        <mesh geometry={nodes.Empty001_3.geometry} material={materials['000000 & Metal (C2,T2)']} />
      </group> */}

      {/* 키오스크 4호관 */}
      {/* <group position={[201.605, 7.1, 148.919]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.766}>
        <mesh geometry={nodes.Empty003.geometry} material={materials['YuhanLogo(B9, Kiosk)']} />
        <mesh geometry={nodes.Empty003_1.geometry} material={materials['D7EFD4 (Kiosk)']} />
        <mesh geometry={nodes.Empty003_2.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane)']} />
        <mesh geometry={nodes.Empty003_3.geometry} material={materials['000000 & Metal (C2,T2)']} />
      </group> */}

       {/* 키오스크 5호관 */}
      {/* <group position={[37.031, 7.1, 80.138]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.766}>
        <mesh geometry={nodes.Empty002.geometry} material={materials['YuhanLogo(B9, Kiosk)']} />
        <mesh geometry={nodes.Empty002_1.geometry} material={materials['D7EFD4 (Kiosk)']} />
        <mesh geometry={nodes.Empty002_2.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane)']} />
        <mesh geometry={nodes.Empty002_3.geometry} material={materials['000000 & Metal (C2,T2)']} />
      </group> */}

       {/* 키오스크 6호관 */}
      {/* <group position={[-15.873, 5.714, 319.606]} rotation={[Math.PI / 2, 0, 0]} scale={0.766}>
        <mesh geometry={nodes.Empty004.geometry} material={materials['YuhanLogo(B9, Kiosk)']} />
        <mesh geometry={nodes.Empty004_1.geometry} material={materials['D7EFD4 (Kiosk)']} />
        <mesh geometry={nodes.Empty004_2.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane)']} />
        <mesh geometry={nodes.Empty004_3.geometry} material={materials['000000 & Metal (C2,T2)']} />
      </group> */}

       {/* 키오스크 7호관 */}
      {/* <group position={[-250.605, 5.899, 93.924]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.766}>
        <mesh geometry={nodes.Empty005.geometry} material={materials['YuhanLogo(B9, Kiosk)']} />
        <mesh geometry={nodes.Empty005_1.geometry} material={materials['D7EFD4 (Kiosk)']} />
        <mesh geometry={nodes.Empty005_2.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane)']} />
        <mesh geometry={nodes.Empty005_3.geometry} material={materials['000000 & Metal (C2,T2)']} />
      </group> */}

       {/* 키오스크 8호관 */}
      {/* <group position={[-301.246, 5.899, -86.629]} rotation={[Math.PI / 2, 0, 0]} scale={0.766}>
        <mesh geometry={nodes.Empty006.geometry} material={materials['YuhanLogo(B9, Kiosk)']} />
        <mesh geometry={nodes.Empty006_1.geometry} material={materials['D7EFD4 (Kiosk)']} />
        <mesh geometry={nodes.Empty006_2.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane)']} />
        <mesh geometry={nodes.Empty006_3.geometry} material={materials['000000 & Metal (C2,T2)']} />
      </group> */}

       {/* 키오스크 1호관 (안쪽) */}
      {/* <group position={[26.272, 5.899, -120.724]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.766}>
        <mesh geometry={nodes.Empty007.geometry} material={materials['YuhanLogo(B9, Kiosk)']} />
        <mesh geometry={nodes.Empty007_1.geometry} material={materials['D7EFD4 (Kiosk)']} />
        <mesh geometry={nodes.Empty007_2.geometry} material={materials['A2A2A2(B9, Park(Rock),B5-6 Plane)']} />
        <mesh geometry={nodes.Empty007_3.geometry} material={materials['000000 & Metal (C2,T2)']} />
      </group> */}

    </group>
  )
}

useGLTF.preload('/assets/models/YuhanMap.glb')
